[project]
name = "CodeUA"
version = "0.1.0"
description = "CodeUA for Ukrainian people"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Andrii Bogdanovych", email = "a@bogdanovych.org" }
]
dependencies = [
  "flet>=0.80.1"
]

[dependency-groups]
dev = [
  "flet[all]>=0.80.1",
]

[tool.flet]
org = "org.bogdanovych"
product = "CodeUA"
company = "Bogdanovych Corp."
copyright = "Copyright (C) 2025 by Andrii Bogdanovych"

[tool.flet.app]
path = "src"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target-version = ['py310']
skip-string-normalization = true

[tool.isort]
profile = "black"

