[project]
name = "CodeUA"
version = "1.0.1"
description = "CodeUA for Ukrainian people"
readme = "README.md"
requires-python = "==3.13"
authors = [
    { name = "Andrii Bogdanovych", email = "ab@foundation101.org" }
]
dependencies = [
  "flet>=0.80.2",
  "flet-audio>=0.80.2"
]

[dependency-groups]
dev = [
  "flet[all]>=0.80.1",
  "flet-audio>=0.80.1"
]

[tool.flet]
org = "org.foundation101"
product = "CodeUA"
company = "Founation.101"
copyright = "Copyright (C) 2026 by Foundation.101"

[tool.flet.app]
path = "src"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target-version = ['py310']
skip-string-normalization = true

[tool.isort]
profile = "black"

